name: 'Commit another repository'

description: 'commit another repository'

inputs:
  repository:
    description: 'repository name, ex) actions/checkout'
    required: true

  refs:
    description: 'ex) refs/heads/master'
    required: false
    default: 'refs/heads/master'

  username:
    description: 'github username'
    required: true

  email:
    description: 'github email'
    required: true

  access_token:
    description: 'personal access token'
    required: true

  command:
    description: 'running command in alpine container'
    required: true

  commit_message:
    description: 'commit message'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.refs }}
    - ${{ inputs.username }}
    - ${{ inputs.access_token }}
    - ${{ inputs.command }}
    - ${{ inputs.commit_message }}
